
name: CI/CD Demo

on: push:
      branches:["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -name: Получение кода
      uses: actions/checkout@v3

      -name:Проверка структуры проекта
      run:echo "Проект успешно получен и готов к сборке"
